### PR TITLE
NXBT-2775: Remove verbosity related to diff on files

### PR DESCRIPTION
**Pull request by alexistimic**
Change INFO log to DEBUG and add a user-friendly log INFO on the executed step

### CODE REVIEW

**Comment by mguillaume** [comment]
"Remove verbosity" - isn't changing INFO to DEBUG the opposite?

**Comment by alexistimic** [comment]
Indeed : `The order of the levels, from least to most verbose, is MSG_ERR, MSG_WARN, MSG_INFO, MSG_VERBOSE, MSG_DEBUG.`

**Comment by jcarsique** [comment]
I don't get the last change. Removing verbosity of the output is:
- increase output level filter if needed: display only INFO or WARN by default, not DEBUG
- decrease message level if to be kept: output on DEBUG level instead of INFO level

So, to me the first change (03c7687957ed822eaf541820d7a8829d6e0ec03c) was correct.
A detail though on the new message: it isn't "not present" but "not present or differ".

**Review by jcarsique — DISMISSED** [review]
:+1: 
can you validate the changes by creating a pipeline mutlibranch job to replace https://qa.nuxeo.org/jenkins/job/Misc/job/tools_ant-assembly-maven-plugin-master/ ?

**Review by jcarsique — DISMISSED** [review]

**Review by jcarsique — DISMISSED** [review]

**Review by andreinechaev — DISMISSED** [review]

**Pull request merged**
